#!/usr/bin/env bash

###########################
# wine runtime selection #
###########################

# On Fedora $SNAP is under /var and there is some magic to map it to /snap.
# # We need to handle that case and reset $SNAP
SNAP=`echo $SNAP | sed -e "s|/var/lib/snapd||g"`

case $(locale) in
  *ru*|*RU*)
    yad --text "Каждый день войны - тысячи смертей мирных украинцев!\n\nКаждый день войны - тысячи смертей российских солдат!\n\nСкажи НЕТ ужасному кровопролитию!\n\nСкажи НЕТ ВОЙНЕ!\n\n" ;;
  * ) ;;
esac

if [ "$SNAP_ARCH" = "amd64" ]; then
  export WINEARCH="win64"
  export ARCH="x86_64-linux-gnu"
  export WINBOX="winbox64.exe"
elif [ "$SNAP_ARCH" = "i386" ]; then
  export WINEARCH="win32"
  export ARCH="i386-linux-gnu"
  export WINBOX="winbox32.exe"
else
  echo "Host architecture ($SNAP_ARCH) unsupported."
  exit 1
fi

export WINEPREFIX=$SNAP_USER_COMMON/.wine
export WINEDLLOVERRIDES="mscoree,mshtml="

if [ "$1" == "winecfg" ]; then
  wine64 winecfg
else
  ln -s -f "${SNAP}/usr/libexec/${WINBOX}" "${TMPDIR}/${WINBOX}"
  ${SNAP}/bin/sommelier "${TMPDIR}/${WINBOX}"
fi
